# nginx.conf
server {
    listen 80;

#     location /a {proxy_pass http://app-a:80;}
#     location /b {proxy_pass http://app-b:80;}
location = /a        { return 200 "exact\n"; }
location ^~ /a/b     { return 200 "prefix-no-regex\n"; }
location ~ ^/a       { return 200 "regex\n"; }
location /a/         { return 200 "prefix\n"; }
location /a/b/c      { return 200 "longest-prefix\n"; }
}
